config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :tweets do
    member do
      get :like
    end
  end
  root "tweets#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/heart.rb
class Heart < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :hearts

  validates_length_of :text, :maximum => 140, :allow_blank => true
  validates :text, presence: true
  validates :username, presence: true
end

def like_count
  hearts.where(like: true).count
end

def not_already_hearted?(user)
  hearts.where(user: user).count == 0
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  before_action :authenticate_user!, except:[:index]
  def index
    @tweets = Tweet.all.order("created_at DESC")
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_name = current_user.email

    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new
    end
  end

  def like
    @tweet = Tweet.find(params[:id])
    if @tweet.not_already_hearted?(current_user)
      @tweet.likes.create(user: current_user)
      redirect_to tweets_path
    else
      redirect_to tweets_path, notice: "sorry, you've already liked this tweet"
    end

  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def tweet_params
      params.require(:tweet).permit(:text, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title
      = Minitwitter

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "#", class: "navbar-brand" do
            %i.fa.fa-twitter{"aria-hidden" => "true"}
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to "Home", root_path
            %li
              = link_to new_tweet_path, class: 'navbar-brand' do
                New Tweet
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li
                %p.navbar-text
                  = current_user.email
            %li
              - if user_signed_in?
                = link_to "LogOut", destroy_user_session_path, method: :delete
              - else
                = link_to "LogIn", new_user_session_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/tweets/_form.html.haml
= form_for @tweet, html: { class: "form-horizontal", role: "form" } do |f|
  -if @tweet.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"

      %ul
        - @tweet.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :text, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :text, class: 'form-control'
  .form-group
    = f.label :username, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :username, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/tweets/edit.html.haml
.page-header
  = link_to tweets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
= render 'form'

app/views/tweets/index.html.haml
.page-header
  %h1 Listing Tweets

.table-responsive
  %table.table.table-striped.table-bordered.table-hover


    %tbody
      - @tweets.each do |tweet|
        %tr
          %td
            %p
              = tweet.hearts.count
              = link_to like_tweet_path(tweet) do
                %i.fa.fa-heart{"aria-hidden" => "true"}
              = tweet.username
              = distance_of_time_in_words_to_now(tweet.created_at)
              ago
            %p
              = tweet.text

app/views/tweets/new.html.haml
.page-header
  = link_to tweets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New tweet

= render 'form'

app/views/tweets/show.html.haml
.page-header
  = link_to tweets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back

%dl.dl-horizontal
  %dt Text:
  %dd= @tweet.text
  %dt Username:
  %dd= @tweet.username